In [1]:
#  imports
import numpy as np
import pandas as pd

# Verify installation and version:
print(f"NumPy version: {np.__version__}")

NumPy version: 2.0.2


In [3]:
# 🌟 Exercise 1 : Array Creation and Manipulation
# Create a 1D NumPy array containing numbers from 0 to 9.

array = np.arange(0,10)

print(array)


[0 1 2 3 4 5 6 7 8 9]


In [7]:
# 🌟 Exercise 2 : Type Conversion and Array Operations
# Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

my_list = [3.14, 2.17, 0, 1, 2]

array = np.array(my_list)

array = array.astype(int)

print(array)


[3 2 0 1 2]


In [8]:
# 🌟 Exercise 3 : Working with Multi-Dimensional Arrays
# Create a 3x3 NumPy array with values ranging from 1 to 9.

array = np.arange(1,10).reshape(3,3)

print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# 🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
# Create a 2D NumPy array of shape (4, 5) filled with random numbers.

np.random.seed(42) #Set seed for reproducibility

random_arr = np.random.random((4, 5)).round(4)
print(random_arr)


[[0.3745 0.9507 0.732  0.5987 0.156 ]
 [0.156  0.0581 0.8662 0.6011 0.7081]
 [0.0206 0.9699 0.8324 0.2123 0.1818]
 [0.1834 0.3042 0.5248 0.4319 0.2912]]


In [12]:
# 🌟 Exercise 5 : Indexing Arrays
# Select the second row from a given 2D NumPy array.

matrix = np.array([ [21, 22, 23, 22, 22],
                    [20, 21, 22, 23, 24],
                    [21, 22, 23, 22, 22]])

print("Matrix:")
print(matrix)
print()

print(f"matrix[1] = {matrix[1, :]} (second row)")
print()

Matrix:
[[21 22 23 22 22]
 [20 21 22 23 24]
 [21 22 23 22 22]]

matrix[1] = [20 21 22 23 24] (second row)



In [14]:
# 🌟 Exercise 6 : Reversing elements
# Reverse the order of elements in a given 1D NumPy array (first element becomes last).

array = np.arange(0, 10)

print(f"Reversed [::-1]: {array[::-1]}")

Reversed [::-1]: [9 8 7 6 5 4 3 2 1 0]


In [15]:
# 🌟 Exercise 7 : Identity Matrix
# Create a 4x4 identity matrix using NumPy.

print("4x4 identity:")
print(np.eye(4))


4x4 identity:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# 🌟 Exercise 8 : Simple Aggregate Funcs
# Find the sum and average of a given 1D array.

array = np.arange(10)
print(f"Array: {array}")
print(f"Sum: {array.sum()}")
print(f"Mean: {array.mean()}")


Array: [0 1 2 3 4 5 6 7 8 9]
Sum: 45
Mean: 4.5


In [23]:
# 🌟 Exercise 9 : Create Array and Change its Structure
# Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

array = np.arange(1,21)
print(f"Array: {array}")
print()
array_reshape = array.reshape(4,5)
print(f"Reshaped array: {array_reshape}")
print(f"Shape of Reshaped array: {array_reshape.shape}")

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Reshaped array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Shape of Reshaped array: (4, 5)


In [24]:
# 🌟 Exercise 10 : Conditional Selection of Values
# Extract all odd numbers from a given NumPy array.

array = np.arange(1,11)

print(f"odd numbers: {array[array % 2 != 0]} ")   # boolean filtering

odd numbers: [1 3 5 7 9] 
